#define LED0_GPIO GPIOA
#define LED1_GPIO GPIOA
#define LED2_GPIO GPIOA

#define LED0_PIN GPIO_PIN_0
#define LED1_PIN GPIO_PIN_5
#define LED2_PIN GPIO_PIN_1


#define SENSE_COMP_GPIO GPIOA
#define SENSE_COMP_PIN GPIO_PIN_2
#define SENSE_A_GPIO GPIOA
#define SENSE_A_PIN GPIO_PIN_7
#define SENSE_B_GPIO GPIOA
#define SENSE_B_PIN GPIO_PIN_6
#define SENSE_C_GPIO GPIOA
#define SENSE_C_PIN GPIO_PIN_4

#define CURRENT_SENSE_GPIO GPIOB
#define CURRENT_SENSE_PIN GPIO_PIN_0

#define PWM_TIM TIM1
#define PWM_CH TIM_CHANNEL_1
#define PWM_CCR TIM1->CCR1
#define PWM_CCER TIM1->CCER
#define PWM_AF GPIO_AF6_TIM1

#define A_FET_HI_GPIO GPIOA
#define A_FET_HI_PIN GPIO_PIN_10
#define A_FET_HI_TIM_CH TIM_CHANNEL_3
#define A_FET_HI_CCR TIM1->CCR3
#define A_FET_HI_AF GPIO_AF6_TIM1

#define B_FET_HI_GPIO GPIOA
#define B_FET_HI_PIN GPIO_PIN_11
#define B_FET_HI_TIM_CH TIM_CHANNEL_4
#define B_FET_HI_CCR TIM1->CCR4
#define B_FET_HI_AF GPIO_AF11_TIM1

#define C_FET_HI_GPIO GPIOA
#define C_FET_HI_PIN GPIO_PIN_9
#define C_FET_HI_TIM_CH TIM_CHANNEL_2
#define C_FET_HI_CCR TIM1->CCR2
#define C_FET_HI_AF GPIO_AF6_TIM1

#define A_FET_LO_GPIO GPIOA
#define A_FET_LO_PIN GPIO_PIN_8
#define B_FET_LO_GPIO GPIOB
#define B_FET_LO_PIN GPIO_PIN_6
#define C_FET_LO_GPIO GPIOB
#define C_FET_LO_PIN GPIO_PIN_7


